properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_RABBITMQ:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  REPLICAS:
    title: Replicas
    description: The number of Pod replicas
    type: integer
    default: 3
    minimum: 1
    maximum: 11
  RABBITMQ_ERLANG_COOKIE:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 32
  RABBITMQ_DEFAULT_USER:
    title: RabbitMQ username
    description: Username to be used for connecting to RabbitMQ
    # TODO(wgrzelak): define pattern
    type: string
    default: rabbit
  RABBITMQ_DEFAULT_PASS:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 12
  RABBITMQ_SERVICE_ACCOUNT:
    type: string
    title: RabbitMQ Service Account
    description: >-
      Service account to assign to RabbitMQ StatefulSet.
      It is required by rabbitmq-peer-discovery-k8s plugin.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: Role
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["endpoints"]
            verbs: ["get"]
required:
- APP_INSTANCE_NAME
- NAMESPACE
- IMAGE_RABBITMQ
- REPLICAS
- RABBITMQ_ERLANG_COOKIE
- RABBITMQ_DEFAULT_USER
- RABBITMQ_DEFAULT_PASS
- RABBITMQ_SERVICE_ACCOUNT
